version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
     - redis
     - mongo
     - mysql
    environment:
     MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis

  mongo:
    image: mongo

  mysql:
    image: mysql
